package org.apache.commons.collections4;

public enum CollectionCommonsRole {
    CONCRETE, ABSTRACT, UNMODIFIABLE, TRANSFORM, INNER, SYNCHRONIZED, DEPRECATED, PREDICATED, COMPOSITE, CONCRETE_DECORATOR, OTHER_DECORATOR
}
